Repository milieuinfo/webcomponent-vl-ui-steps, pull requests merged in 2020-07, with the labels that each got.

#14 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#15 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
Labels: bug

#16 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
